name: CD/CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Docker 🐋
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dashboard to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub 🐋
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: baaarbz/portfolio-web:latest

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy 🚀
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy the application 🚀
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop portfolio-web
            docker rmi baaarbz/portfolio-web
            docker pull baaarbz/portfolio-web:latest
            docker run -d -p 3000:3000 --restart always --name portfolio-web baaarbz/portfolio-web:latest